In [141]:
# Reverse any given String
s = 'abhishek maity'
s[::-1]

'ytiam kehsihba'

In [25]:
# taking input from the user dynamically

lst = []
n = int(input("Total numbers you want to sort : "))

for i in range(n):
    a = int(input("Please enter a number : "))
    lst.append(a)
    


Total numbers you want to sort : 3
Please enter a number : 12
Please enter a number : 13
Please enter a number : 0


In [142]:
# Swapcase() function in python
name = 'AbhiSHek MaITY'
print(name.swapcase())

aBHIshEK mAity


In [170]:
ord('A'), ord('Z'), ord('a'), ord('z')

(65, 90, 97, 122)

In [188]:
97-65

32

In [178]:
ord(' ')

32

In [211]:
i = ' '
chr(ord(str(i))+32)

'@'

In [232]:
import numpy as np
np.arange(97,123)

array([ 97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109,
       110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122])

# SwapCase in python without using the inbuilt function

In [235]:
def swapcase(sentence):
    res = ''
    for i in sentence :
        if ord(i) in np.arange(65,98):
            res = res + chr(ord(i)+32)
        elif ord(i) in np.arange(97,123):
            res = res + chr(ord(i)-32)
        else :
            res = res + i
                
    return res
        
        
res = swapcase('Abhishek Maity')
res

'aBHISHEK m\x81ITY'

In [418]:
ord('\x81')

129

In [419]:
129-32

97

In [422]:
def swapcase(sentence):
    res = ''
    for i in sentence :
        if 65 <= ord(i) <= 95:
            res = res + chr(ord(i)+32)
        elif 97 <= ord(i) <= 122:
            res = res + chr(ord(i)-32)
        else :
            res = res + i
                
    return res
        
        
res = swapcase('Abhishek Maity fgFGH --==@657')
res       

'aBHISHEK mAITY FGfgh --==@657'

'aISEKmAIY'

In [57]:
name = 'AbhiSHek MaITY'
chr(110000)

'\U0001adb0'

## ord()  ,  chr() methods 

In [46]:
ord('A')

65

In [47]:
chr(65)

'A'

In [91]:
ord('a')

97

# Numpy in python

In [249]:
lst = []
for i in (np.linspace(1,10,100)):
    i = np.round(i,2)
    lst.append(i)

In [255]:
lst = np.array(lst)
lst.reshape((10,10))

array([[ 1.  ,  1.09,  1.18,  1.27,  1.36,  1.45,  1.55,  1.64,  1.73,
         1.82],
       [ 1.91,  2.  ,  2.09,  2.18,  2.27,  2.36,  2.45,  2.55,  2.64,
         2.73],
       [ 2.82,  2.91,  3.  ,  3.09,  3.18,  3.27,  3.36,  3.45,  3.55,
         3.64],
       [ 3.73,  3.82,  3.91,  4.  ,  4.09,  4.18,  4.27,  4.36,  4.45,
         4.55],
       [ 4.64,  4.73,  4.82,  4.91,  5.  ,  5.09,  5.18,  5.27,  5.36,
         5.45],
       [ 5.55,  5.64,  5.73,  5.82,  5.91,  6.  ,  6.09,  6.18,  6.27,
         6.36],
       [ 6.45,  6.55,  6.64,  6.73,  6.82,  6.91,  7.  ,  7.09,  7.18,
         7.27],
       [ 7.36,  7.45,  7.55,  7.64,  7.73,  7.82,  7.91,  8.  ,  8.09,
         8.18],
       [ 8.27,  8.36,  8.45,  8.55,  8.64,  8.73,  8.82,  8.91,  9.  ,
         9.09],
       [ 9.18,  9.27,  9.36,  9.45,  9.55,  9.64,  9.73,  9.82,  9.91,
        10.  ]])

# Key Differences

- In Array we can do direct operations which will get applied to all the elements in array but in list its not
- We can extend the size of the list but not the size of the array
- convert back to array to list using tolist() function
- every item in an array should be of that datatype only!
- Occupies less space than the python list


In [272]:
a = np.array([3,4])

In [275]:
a+100

array([103, 104])

In [284]:
lst = [np.max([1,2,3]),2,3,4,5]
lst+100

TypeError: can only concatenate list (not "int") to list

In [293]:
arr = np.array([np.arange(10)])
arr

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [294]:
arr.shape

(1, 10)

In [295]:
arr.dtype

dtype('int32')

In [296]:
arr.size

10

In [297]:
arr.ndim

2

In [299]:
arr = np.arange(100).reshape(10,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [300]:
arr[3:8,3:7]

array([[33, 34, 35, 36],
       [43, 44, 45, 46],
       [53, 54, 55, 56],
       [63, 64, 65, 66],
       [73, 74, 75, 76]])

In [305]:
arr[:,0:1]/100

array([[0. ],
       [0.1],
       [0.2],
       [0.3],
       [0.4],
       [0.5],
       [0.6],
       [0.7],
       [0.8],
       [0.9]])

In [306]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [318]:
# Reverse only Row positions 
arr[::,::-1]

array([[ 9,  8,  7,  6,  5,  4,  3,  2,  1,  0],
       [19, 18, 17, 16, 15, 14, 13, 12, 11, 10],
       [29, 28, 27, 26, 25, 24, 23, 22, 21, 20],
       [39, 38, 37, 36, 35, 34, 33, 32, 31, 30],
       [49, 48, 47, 46, 45, 44, 43, 42, 41, 40],
       [59, 58, 57, 56, 55, 54, 53, 52, 51, 50],
       [69, 68, 67, 66, 65, 64, 63, 62, 61, 60],
       [79, 78, 77, 76, 75, 74, 73, 72, 71, 70],
       [89, 88, 87, 86, 85, 84, 83, 82, 81, 80],
       [99, 98, 97, 96, 95, 94, 93, 92, 91, 90]])

In [321]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [338]:
arr[3,5]=arr[3,5]*int(np.nan)
arr[3,5]

ValueError: cannot convert float NaN to integer

In [339]:
arr

array([[     0,      1,      2,      3,      4,      5,      6,      7,
             8,      9],
       [    10,     11,     12,     13,     14,     15,     16,     17,
            18,     19],
       [    20,     21,     22,     23,     24,     25,     26,     27,
            28,     29],
       [    30,     31,     32,     33,     34, 555555,     36,     37,
            38,     39],
       [    40,     41,     42,     43,     44,     45,     46,     47,
            48,     49],
       [    50,     51,     52,     53,     54,     55,     56,     57,
            58,     59],
       [    60,     61,     62,     63,     64,     65,     66,     67,
            68,     69],
       [    70,     71,     72,     73,     74,     75,     76,     77,
            78,     79],
       [    80,     81,     82,     83,     84,     85,     86,     87,
            88,     89],
       [    90,     91,     92,     93,     94,     95,     96,     97,
            98,     99]])

In [340]:
arr2 = arr.copy()

In [347]:
arr

array([[     0,      1,      2,      3,      4,      5,      6,      7,
             8,      9],
       [    10,     11,     12,     13,     14,     15,     16,     17,
            18,     19],
       [    20,     21,     22,     23,     24,     25,     26,     27,
            28,     29],
       [    30,     31,     32,     33,     34, 555555,     36,     37,
            38,     39],
       [    40,     41,     42,     43,     44,     45,     46,     47,
            48,     49],
       [    50,     51,     52,     53,     54,     55,     56,     57,
            58,     59],
       [    60,     61,     62,     63,     64,     65,     66,     67,
            68,     69],
       [    70,     71,     72,     73,     74,     75,     76,     77,
            78,     79],
       [    80,     81,     82,     83,     84,     85,     86,     87,
            88,     89],
       [    90,     91,     92,     93,     94,     95,     96,     97,
            98,     99]])

In [348]:
arr2 = arr2[::-1,]*100
arr2

array([[         0,      10000,      20000,      30000,      40000,
             50000,      60000,      70000,      80000,      90000],
       [    100000,     110000,     120000,     130000,     140000,
            150000,     160000,     170000,     180000,     190000],
       [    200000,     210000,     220000,     230000,     240000,
            250000,     260000,     270000,     280000,     290000],
       [    300000,     310000,     320000,     330000,     340000,
        1260582704,     360000,     370000,     380000,     390000],
       [    400000,     410000,     420000,     430000,     440000,
            450000,     460000,     470000,     480000,     490000],
       [    500000,     510000,     520000,     530000,     540000,
            550000,     560000,     570000,     580000,     590000],
       [    600000,     610000,     620000,     630000,     640000,
            650000,     660000,     670000,     680000,     690000],
       [    700000,     710000,     72000

# Flatten() and Ravel()

- Flatten() creates a new copy of the array and any changes dont reflect to old array
- Ravel() just creates a reference of the original array and any changes will reflect the main one


# np.repeat() and np.tile()

- np.tile() will repeat the whole list or array n times
- np.repeat() will repeat each of the members n times



In [403]:
lst = [1,2,3,4,5]
np.repeat(lst,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [425]:
np.tile(lst,2).reshape(2,5)

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

# Generating Random numbers

In [351]:
np.random.random() # generates random number between 0-1

0.2839124443917339

In [360]:
np.random.randn(1,10) # createsrandom nos. of std normal form... mean = 0 std dev =1

array([[-1.24864354, -1.74038291,  0.39340169,  0.48522848,  0.46137091,
        -0.89070589, -1.95464971, -0.4726289 , -0.45495975,  0.73328753]])

In [370]:
np.random.randint(0,10, size=(2,2))

array([[3, 7],
       [4, 8]])

In [393]:
np.random.choice(['a', 'e', 'i', 'o', 'u'],2)

array(['u', 'a'], dtype='<U1')

In [382]:
list('aeiou')

['a', 'e', 'i', 'o', 'u']

In [398]:
rp = np.random.randint(1,10,11)
rp

array([6, 6, 3, 4, 3, 5, 1, 3, 5, 3, 7])

In [400]:
np.unique(rp, return_counts=True)

(array([1, 3, 4, 5, 6, 7]), array([1, 4, 1, 2, 2, 1], dtype=int64))

In [408]:
import pandas as pd
data = {'A' : ['aa','bb', 'ac', 'fgca'],
        'B' : ['aaa','bbb', 'ac', 'fgca']}
df = pd.DataFrame(data)
df

A     B
0    aa   aaa
1    bb   bbb
2    ac    ac
3  fgca  fgca

In [417]:
df[df['A'].str.contains('ac')]

A   B
2  ac  ac