# Numpy101

## Swap Case function in python

In [142]:
# Swapcase() function in python
name = 'AbhiSHek MaITY'
print(name.swapcase())

aBHIshEK mAity


### simple method to reverse any string

In [818]:
# Reverse any given String
s = 'abhishek maity'
s[::-1]

'ytiam kehsihba'

In [820]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [821]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### ord() and chr()

In [170]:
ord('A'), ord('Z'), ord('a'), ord('z')

(65, 90, 97, 122)

In [188]:
97-65

32

In [178]:
ord(' ')

32

In [211]:
i = ' '
chr(ord(str(i))+32)

'@'

In [232]:
import numpy as np
np.arange(97,123)

array([ 97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109,
       110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122])

# SwapCase in python without using the inbuilt function

In [822]:
def swapcase(sentence):
    res = ''
    for i in sentence :
        if ord(i) in np.arange(65,96):
            res = res + chr(ord(i)+32)
        elif ord(i) in np.arange(97,123):
            res = res + chr(ord(i)-32)
        else :
            res = res + i
                
    return res
        
        
res = swapcase('Abhishek Maity')
res

'aBHISHEK mAITY'

In [823]:
def swapcase(sentence):
    res = ''
    for i in sentence :
        if 65 <= ord(i) <= 95:
            res = res + chr(ord(i)+32)
        elif 97 <= ord(i) <= 122:
            res = res + chr(ord(i)-32)
        else :
            res = res + i
                
    return res
        
        
res = swapcase('Abhishek Maity fgFGH --==@657')
res       

'aBHISHEK mAITY FGfgh --==@657'

In [57]:
name = 'AbhiSHek MaITY'
chr(110000)

'\U0001adb0'

## ord()  ,  chr() methods 

- ord() is basically used to find the order... ie.. ASCII value of any character
- chr() is mainly used to find the specific character given input as ASCII number

In [46]:
ord('A')

65

In [47]:
chr(65)

'A'

In [91]:
ord('a')

97

# Numpy in python

In [824]:
lst = []
for i in (np.linspace(1,10,100)):
    i = np.round(i,2)
    lst.append(i)

In [826]:
lst = np.array(lst)
lst.reshape((10,10))

array([[ 1.  ,  1.09,  1.18,  1.27,  1.36,  1.45,  1.55,  1.64,  1.73,
         1.82],
       [ 1.91,  2.  ,  2.09,  2.18,  2.27,  2.36,  2.45,  2.55,  2.64,
         2.73],
       [ 2.82,  2.91,  3.  ,  3.09,  3.18,  3.27,  3.36,  3.45,  3.55,
         3.64],
       [ 3.73,  3.82,  3.91,  4.  ,  4.09,  4.18,  4.27,  4.36,  4.45,
         4.55],
       [ 4.64,  4.73,  4.82,  4.91,  5.  ,  5.09,  5.18,  5.27,  5.36,
         5.45],
       [ 5.55,  5.64,  5.73,  5.82,  5.91,  6.  ,  6.09,  6.18,  6.27,
         6.36],
       [ 6.45,  6.55,  6.64,  6.73,  6.82,  6.91,  7.  ,  7.09,  7.18,
         7.27],
       [ 7.36,  7.45,  7.55,  7.64,  7.73,  7.82,  7.91,  8.  ,  8.09,
         8.18],
       [ 8.27,  8.36,  8.45,  8.55,  8.64,  8.73,  8.82,  8.91,  9.  ,
         9.09],
       [ 9.18,  9.27,  9.36,  9.45,  9.55,  9.64,  9.73,  9.82,  9.91,
        10.  ]])

# Key Differences

- In Array we can do direct operations which will get applied to all the elements in array but in list its not
- We can extend the size of the list but not the size of the array
- convert back to array to list using tolist() function
- every item in an array should be of that datatype only!
- Occupies less space than the python list


In [272]:
a = np.array([3,4])

In [275]:
a+100

array([103, 104])

In [284]:
lst = [np.max([1,2,3]),2,3,4,5]
lst+100

TypeError: can only concatenate list (not "int") to list

In [293]:
arr = np.array([np.arange(10)])
arr

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [294]:
arr.shape

(1, 10)

In [484]:
(arr.dtype)

dtype('int32')

In [296]:
arr.size

10

In [297]:
arr.ndim

2

In [828]:
arr = np.arange(100).reshape(10,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [829]:
### Array slicing
arr[3:8,3:7]

array([[33, 34, 35, 36],
       [43, 44, 45, 46],
       [53, 54, 55, 56],
       [63, 64, 65, 66],
       [73, 74, 75, 76]])

In [830]:
arr[:,0:1]/100

array([[0. ],
       [0.1],
       [0.2],
       [0.3],
       [0.4],
       [0.5],
       [0.6],
       [0.7],
       [0.8],
       [0.9]])

In [831]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [834]:
arr[::-1,::] # reversinig only with the row positions

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [836]:
#### Reverse only column positions 
arr[::,::-1]

array([[ 9,  8,  7,  6,  5,  4,  3,  2,  1,  0],
       [19, 18, 17, 16, 15, 14, 13, 12, 11, 10],
       [29, 28, 27, 26, 25, 24, 23, 22, 21, 20],
       [39, 38, 37, 36, 35, 34, 33, 32, 31, 30],
       [49, 48, 47, 46, 45, 44, 43, 42, 41, 40],
       [59, 58, 57, 56, 55, 54, 53, 52, 51, 50],
       [69, 68, 67, 66, 65, 64, 63, 62, 61, 60],
       [79, 78, 77, 76, 75, 74, 73, 72, 71, 70],
       [89, 88, 87, 86, 85, 84, 83, 82, 81, 80],
       [99, 98, 97, 96, 95, 94, 93, 92, 91, 90]])

In [838]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [839]:
arr[3,5]=arr[3,5]*int(np.nan)
arr[3,5]

ValueError: cannot convert float NaN to integer

In [840]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [340]:
arr2 = arr.copy()

In [347]:
arr

array([[     0,      1,      2,      3,      4,      5,      6,      7,
             8,      9],
       [    10,     11,     12,     13,     14,     15,     16,     17,
            18,     19],
       [    20,     21,     22,     23,     24,     25,     26,     27,
            28,     29],
       [    30,     31,     32,     33,     34, 555555,     36,     37,
            38,     39],
       [    40,     41,     42,     43,     44,     45,     46,     47,
            48,     49],
       [    50,     51,     52,     53,     54,     55,     56,     57,
            58,     59],
       [    60,     61,     62,     63,     64,     65,     66,     67,
            68,     69],
       [    70,     71,     72,     73,     74,     75,     76,     77,
            78,     79],
       [    80,     81,     82,     83,     84,     85,     86,     87,
            88,     89],
       [    90,     91,     92,     93,     94,     95,     96,     97,
            98,     99]])

In [348]:
arr2 = arr2[::-1,]*100
arr2

array([[         0,      10000,      20000,      30000,      40000,
             50000,      60000,      70000,      80000,      90000],
       [    100000,     110000,     120000,     130000,     140000,
            150000,     160000,     170000,     180000,     190000],
       [    200000,     210000,     220000,     230000,     240000,
            250000,     260000,     270000,     280000,     290000],
       [    300000,     310000,     320000,     330000,     340000,
        1260582704,     360000,     370000,     380000,     390000],
       [    400000,     410000,     420000,     430000,     440000,
            450000,     460000,     470000,     480000,     490000],
       [    500000,     510000,     520000,     530000,     540000,
            550000,     560000,     570000,     580000,     590000],
       [    600000,     610000,     620000,     630000,     640000,
            650000,     660000,     670000,     680000,     690000],
       [    700000,     710000,     72000

# Flatten() and Ravel()

- Flatten() creates a new copy of the array and any changes dont reflect to old array
- Ravel() just creates a reference of the original array and any changes will reflect the main one


# np.repeat() and np.tile()

- np.tile() will repeat the whole list or array n times
- np.repeat() will repeat each of the members n times



In [485]:
lst = [1,2,3,4,5]
np.repeat(lst,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [487]:
np.tile(lst,2).reshape(2,5)

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

# Generating Random numbers

In [509]:
np.random.random() # generates random number between 0-1

0.06150331746249793

In [360]:
np.random.randn(1,10) # creates random nos. of std normal form... mean = 0 std dev =1

array([[-1.24864354, -1.74038291,  0.39340169,  0.48522848,  0.46137091,
        -0.89070589, -1.95464971, -0.4726289 , -0.45495975,  0.73328753]])

In [497]:
np.random.randint(0,10, size=(3,3))

array([[9, 5, 3],
       [8, 5, 6],
       [6, 1, 0]])

In [846]:
np.random.choice(['a', 'e', 'i', 'o', 'u'],2)

array(['u', 'i'], dtype='<U1')

In [382]:
list('aeiou')

['a', 'e', 'i', 'o', 'u']

In [514]:
rp = np.random.randint(1,10,11)
rp

array([6, 9, 2, 9, 9, 1, 2, 8, 2, 1, 2])

In [524]:
np.unique(rp, return_counts=True)

(array([1, 2, 6, 8, 9]), array([2, 4, 1, 1, 3], dtype=int64))

In [408]:
import pandas as pd
data = {'A' : ['aa','bb', 'ac', 'fgca'],
        'B' : ['aaa','bbb', 'ac', 'fgca']}
df = pd.DataFrame(data)
df

A     B
0    aa   aaa
1    bb   bbb
2    ac    ac
3  fgca  fgca

In [417]:
df[df['A'].str.contains('ac')]

A   B
2  ac  ac

## np.where()

In [850]:
arr = np.random.randint(1,10,20)
arr

array([3, 8, 2, 7, 7, 1, 8, 3, 4, 6, 5, 3, 5, 4, 8, 1, 1, 6, 7, 7])

In [859]:
np.where(arr>2)

(array([ 0,  1,  3,  4,  6,  7,  8,  9, 10, 11, 12, 13, 14, 17, 18, 19],
       dtype=int64),)

In [540]:
res = np.where(arr>5,100,arr)

In [541]:
res

array([  1, 100, 100,   2,   3,   5, 100, 100, 100,   4, 100,   1, 100,
       100,   1,   5,   3,   1,   4,   1])

In [543]:
res_index = np.where(arr>5)
res_index

(array([ 1,  2,  6,  7,  8, 10, 12, 13], dtype=int64),)

## .take()

In [548]:
arr.take(res_index)

array([[6, 7, 6, 6, 9, 9, 7, 8]])

### np.argmax() np.argmin()

In [552]:
arr

array([1, 6, 7, 2, 3, 5, 6, 6, 9, 4, 9, 1, 7, 8, 1, 5, 3, 1, 4, 1])

In [553]:
np.argmin(arr), np.argmax(arr)

(0, 8)

In [861]:
def find_max(n):
    mx = -999999999
    for i in arr:
        if i > mx:
            i, mx = mx, i
    return mx

print(find_max(arr))
    

8


### How to import and export data as a csv file?


In [ ]:
data = np.genfromtxt(path, delimiter = ',', skip_header=1, dtype=None)

### Exporting the array as a csv file

In [ ]:
np.savetxt("out.csv", data, delimiter=',')

In [ ]:
np.savez('array.npz', data1, data2) # saves multiple arrays as a .npz file
np.save('myarray.npy', data1) # saves single array as a npy file

np.load('myarray.npy') # to load the data back 

## Concatenate 2 numpy arrays column wise and row wise

- np.concatenate() by changing the axis param 0 or 1
- np.vstack() and  np.hstack()
- np.r_ and np.c_

All will provide the same output

In [557]:
a = np.zeros((2,4))
b = np.ones((3,4))

In [558]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [559]:
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [566]:
np.concatenate([a,b],axis=0)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [569]:
np.vstack([a, b])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### array sorting

In [866]:
arr = np.random.randint(1, 6, size=(8,4))

In [867]:
arr

array([[3, 5, 3, 4],
       [4, 2, 3, 4],
       [1, 2, 2, 4],
       [1, 5, 3, 5],
       [4, 5, 5, 3],
       [1, 2, 1, 5],
       [3, 5, 5, 2],
       [1, 2, 1, 5]])

In [868]:
np.sort(arr,axis=1)

array([[3, 3, 4, 5],
       [2, 3, 4, 4],
       [1, 2, 2, 4],
       [1, 3, 5, 5],
       [3, 4, 5, 5],
       [1, 1, 2, 5],
       [2, 3, 5, 5],
       [1, 1, 2, 5]])

## np.argsort()

- np.argsort() does is that it returns the index positions of that would make a given 1d array sorted

In [869]:
np.argsort(arr,axis=1)

array([[0, 2, 3, 1],
       [1, 2, 0, 3],
       [0, 1, 2, 3],
       [0, 2, 1, 3],
       [3, 0, 1, 2],
       [0, 2, 1, 3],
       [3, 0, 1, 2],
       [0, 2, 1, 3]], dtype=int64)

In [870]:
arr

array([[3, 5, 3, 4],
       [4, 2, 3, 4],
       [1, 2, 2, 4],
       [1, 5, 3, 5],
       [4, 5, 5, 3],
       [1, 2, 1, 5],
       [3, 5, 5, 2],
       [1, 2, 1, 5]])

### Only sorting the first column of the matrix and not the other columns

using **np.argsort()**

In [872]:
arr[:,0] # only fetching the 1st column of the matrix

array([3, 4, 1, 1, 4, 1, 3, 1])

In [886]:
arr[:,arr[2,:].argsort()] ## sorting by specific row

array([[3, 5, 3, 4],
       [4, 2, 3, 4],
       [1, 2, 2, 4],
       [1, 5, 3, 5],
       [4, 5, 5, 3],
       [1, 2, 1, 5],
       [3, 5, 5, 2],
       [1, 2, 1, 5]])

In [875]:
sorted_index = arr[:,1].argsort()
sorted_index ##### sorting with the 1st column only 

array([1, 2, 5, 7, 0, 3, 4, 6], dtype=int64)

In [876]:
arr[sorted_index] ##### then place the same sorted index in the array 

array([[4, 2, 3, 4],
       [1, 2, 2, 4],
       [1, 2, 1, 5],
       [1, 2, 1, 5],
       [3, 5, 3, 4],
       [1, 5, 3, 5],
       [4, 5, 5, 3],
       [3, 5, 5, 2]])

In [603]:
## to sort it in desc order
arr[sorted_index[::-1]]

array([[5, 4, 5, 1],
       [5, 2, 4, 1],
       [5, 1, 3, 4],
       [4, 3, 2, 5],
       [3, 1, 4, 2],
       [2, 5, 1, 1],
       [2, 2, 2, 2],
       [1, 5, 2, 4]])

## Sorting numpy array based on 2 or more columns

using **np.lexsort()**

In [604]:
# Sort by column 0 then by column 1.. ?

In [608]:
arr = np.random.randint(1,10,[5,5])
arr

array([[2, 9, 3, 7, 7],
       [6, 7, 4, 1, 3],
       [1, 3, 1, 5, 9],
       [9, 7, 3, 5, 8],
       [1, 5, 8, 5, 9]])

In [616]:
arr[:,:1]

array([[2],
       [6],
       [1],
       [9],
       [1]])

In [617]:
arr[:,0], arr[:,1]

(array([2, 6, 1, 9, 1]), array([9, 7, 3, 7, 5]))

### NOTE : column to be sorted first place it the right most side!!!

In [618]:
lexsorted = np.lexsort([arr[:,1], arr[:,0]])

In [619]:
lexsorted

array([2, 4, 0, 1, 3], dtype=int64)

In [620]:
arr[lexsorted]

array([[1, 3, 1, 5, 9],
       [1, 5, 8, 5, 9],
       [2, 9, 3, 7, 7],
       [6, 7, 4, 1, 3],
       [9, 7, 3, 5, 8]])

## Advance numpy functions

If you want to make a function work on both the **scalar** and **vector** values then use **np.vectorize()**

In [887]:
def foo(x) :
    if x%2 == 0 :
        return x**2
    else :
        return x/2
    
    
print(foo(9))
    
    

4.5


In [627]:
print(foo[1,2,3])

TypeError: 'function' object is not subscriptable

In [638]:
foo_vector = np.vectorize(foo, otypes=[float])

In [639]:
foo_vector([4,9,10])

array([ 16. ,   4.5, 100. ])

In [642]:
foo_vector(2)

array(1.15)

## apply_along_axis - Apply a function *column wise* or *row wise*


We can do this by using any for loop also 

In [890]:
np.random.seed(100)
arr = np.random.randint(1,10,(4,10))
arr

array([[9, 9, 4, 8, 8, 1, 5, 3, 6, 3],
       [3, 3, 2, 1, 9, 5, 1, 7, 3, 5],
       [2, 6, 4, 5, 5, 4, 8, 2, 2, 8],
       [8, 1, 3, 4, 3, 6, 9, 2, 1, 8]])

In [897]:
np.apply_along_axis(lambda x :x*10, 1, arr)

array([[90, 90, 40, 80, 80, 10, 50, 30, 60, 30],
       [30, 30, 20, 10, 90, 50, 10, 70, 30, 50],
       [20, 60, 40, 50, 50, 40, 80, 20, 20, 80],
       [80, 10, 30, 40, 30, 60, 90, 20, 10, 80]])

### How to find the difference between maximum and minimum value in each row?

using **np.apply_along_axis()**

In [648]:
def max_min_res(x):
    return np.max(x) - np.min(x)

print('Row wise : {}'.format(np.apply_along_axis(max_min_res, 1, arr)))
print('Column wise : {}'.format(np.apply_along_axis(max_min_res, 0, arr)))




Row wise : [8 8 6 8]
Column wise : [7 8 2 7 6 5 8 5 5 5]


# Finding the location to insert so that the array will remain sorted

**np.searchsorted()**

In [898]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [656]:
np.searchsorted(arr, 7.5)

8

## Adding additional axis to a numpy array

**np.newaxis()**

In [899]:
arr = np.arange(5)
print(arr)
print('shape of array is : ',arr.shape)

[0 1 2 3 4]
shape of array is :  (5,)


In [668]:
arr[np.newaxis,np.newaxis,:]

array([[[0, 1, 2, 3, 4]]])

In [670]:
arr.reshape((5,1))

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [673]:
arr[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

## Digitize

np.digitize() --> to return the index position of the bin which element belongs to 

In [ ]:
np.digitize()

# Clip

- **np.clip()**       . to cap the numbers within a given cutoff range.
- all the nos. below the lower limit will be replaced by lower limit and same with higher limit

In [675]:
arr

array([0, 1, 2, 3, 4])

In [680]:
np.clip(arr, -3,-1)

array([-1, -1, -1, -1, -1])

# Histogram() and Bincount()

gives the frequency counts of the bins

In [900]:
x = np.array([1,1,2,2,2,4,4,5,6,6,6])
x

array([1, 1, 2, 2, 2, 4, 4, 5, 6, 6, 6])

In [682]:
np.bincount(x)

array([0, 2, 3, 0, 2, 1, 3], dtype=int64)

In [683]:
from collections import Counter

In [684]:
Counter(x)

Counter({1: 2, 2: 3, 4: 2, 5: 1, 6: 3})

In [685]:
np.histogram(x, [1,2,4,6])

(array([2, 3, 6], dtype=int64), array([1, 2, 4, 6]))

- No direct function to merge two 2d arrays based on a common column 
- Cant create pivot tables directly
- No direct way of doing 2d cross tabulations

## ------------------------------------------------------Finish-------------------------------------------------------------------

In [701]:
class A:
    __a=90
    def  __init__(self,a,b,c):
        self.a = a
        self.b = b
        self.c = c
        
    @classmethod
    def show(cls,txt):
        a,b,c = txt.split('-')
        return cls(a,b,c)
        
            
        

In [709]:
a= A.show('Abhishek-Data-Science')
a.show('Maity-Bittu-Ab')

In [722]:
x = [23,4,51,22,1]
print(x)

[23, 4, 51, 22, 1]


In [723]:
print(sorted(x))

[1, 4, 22, 23, 51]


In [732]:
x[2]

51

In [739]:
for i,j in enumerate(x,-5):
    print(i)

-5
-4
-3
-2
-1


In [751]:
x=[]
y=[]
for i in ['abhishek','maity','Data', 'python']:
    x.append('=='.join(i))
    y.append(i)
print(x)
print(y)

['a==b==h==i==s==h==e==k', 'm==a==i==t==y', 'D==a==t==a', 'p==y==t==h==o==n']
['abhishek', 'maity', 'Data', 'python']


In [756]:
arr = np.arange(40).reshape(10,-1)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [777]:
arr[-1,:]

array([36, 37, 38, 39])

In [720]:
x.sort(reverse=True)

In [778]:
x

['a==b==h==i==s==h==e==k', 'm==a==i==t==y', 'D==a==t==a', 'p==y==t==h==o==n']

In [785]:
r = iter(x)

In [700]:
a,b,c='abhishek-maity-hi'.split('-')
a

'abhishek'

In [902]:
############ example to named tuple
from collections import namedtuple
s = namedtuple('AbhishekM',['red','blue','green'])
tp = s(0,255,200)
print(tp)
print(tp.red,tp.green,tp.blue)

AbhishekM(red=0, blue=255, green=200)
0 200 255


In [901]:
######## example of custom error handling
class Custom(Exception):
    pass
class negative(Custom):
    pass


try :
    num = int(input("Enter n : "))
    if num>0:
        print("The number is {}".format(num))
        
    else :
        raise negative

        
except negative:
    print("Please enter a positive number!!!")
    
except Exception as ex:
    print(ex)
    
finally :
    print("FINALLY BLOCK WILL BE EXECUTED ANY HOW !!!! ")
    

Enter n : 34
The number is 34
FINALLY BLOCK WILL BE EXECUTED ANY HOW !!!! 
