# Pandas 101

In [1]:
import numpy as np
import pandas as pd

In [3]:
pd.__version__

'1.2.1'

In [12]:
pd.show_versions(as_json=True)

{'system': {'commit': '9d598a5e1eee26df95b3910e3f2934890d062caa', 'python': '3.7.9.final.0', 'python-bits': 64, 'OS': 'Windows', 'OS-release': '10', 'Version': '10.0.19041', 'machine': 'AMD64', 'processor': 'Intel64 Family 6 Model 158 Stepping 10, GenuineIntel', 'byteorder': 'little', 'LC_ALL': None, 'LANG': None, 'LOCALE': {'language-code': None, 'encoding': None}}, 'dependencies': {'pandas': '1.2.1', 'numpy': '1.19.2', 'pytz': '2020.4', 'dateutil': '2.8.1', 'pip': '20.2.4', 'setuptools': '50.3.0.post20201006', 'Cython': '0.29.14', 'pytest': None, 'hypothesis': None, 'sphinx': '3.3.0', 'blosc': None, 'feather': None, 'xlsxwriter': None, 'lxml.etree': '4.6.2', 'html5lib': None, 'pymysql': None, 'psycopg2': None, 'jinja2': '2.11.1', 'IPython': '7.19.0', 'pandas_datareader': None, 'bs4': '4.9.3', 'bottleneck': None, 'fsspec': None, 'fastparquet': None, 'gcsfs': None, 'matplotlib': '3.3.2', 'numexpr': None, 'odfpy': None, 'openpyxl': None, 'pandas_gbq': None, 'pyarrow': '3.0.0', 'pyxlsb':

# Making a Series from list, array, dictionary

In [652]:
lst = [1,2,3,4,5]
arr = np.array(lst)
dct = dict(zip(lst,arr))

pd.Series(dct)


1    1
2    2
3    3
4    4
5    5
dtype: int64

In [1552]:
list(zip(lst,arr,[1,2,3,4,5,6,8]))

[(3, 1, 1), (6, 2, 2), (9, 3, 3), (12, 4, 4), (15, 5, 5)]

## Converting Series to DataFrame

In [1553]:
lst = list('abcdefghijklmnopqrstuvwxyz')
arr = np.arange(26)
dct = dict(zip(lst,arr))

In [79]:
ser = pd.Series(dct)

In [90]:
df = pd.DataFrame(ser).reset_index()
df2 = ser.to_frame().reset_index()

In [92]:
df.head()

index  0
0     a  0
1     b  1
2     c  2
3     d  3
4     e  4

In [101]:
ser1 = pd.Series(list('abhishekmaity'))
ser2 = pd.Series(np.arange(13))

In [105]:
df = pd.concat([ser1, ser2], axis=1)
df2 = pd.DataFrame({'col1' : ser1, 'col2' : ser2})

In [106]:
df2.head()

col1  col2
0    a     0
1    b     1
2    h     2
3    i     3
4    s     4

In [1559]:
ss = pd.Series(list('abhishek'))

In [1560]:
ss.name = 'myname'

In [1561]:
ss

0    a
1    b
2    h
3    i
4    s
5    h
6    e
7    k
Name: myname, dtype: object

# getting items in Series A not present in Series B

In [127]:
ser1 = pd.Series([1,2,3,4,5])
ser2 = pd.Series([4,5,6,7,8])

### .add_suffix()  & .add_prefix()

In [136]:
print(ser1.add_suffix('_last')), print(ser2.add_prefix('abc_'))

0_last    1
1_last    2
2_last    3
3_last    4
4_last    5
dtype: int64
abc_0    4
abc_1    5
abc_2    6
abc_3    7
abc_4    8
dtype: int64


(None, None)

In [140]:
ser1[~ser1.isin(ser2)] # in pandas if you put ~ in front of any filter condition then it will become not

0    1
1    2
2    3
dtype: int64

In [1562]:
ser1 = pd.Series([1,2,3,4,5])
ser2 = pd.Series([4,5,6,7,8])

ser_union = pd.Series(np.union1d(ser1, ser2)) # union will join both ... but common ones will consider once only
ser_intersection = pd.Series(np.intersect1d(ser1, ser2)) # intersect will take only common between both

In [1564]:
np.union1d(ser1, ser2)

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [152]:
ser_not_common = ser_union[~ser_union.isin(ser_intersection)]
ser_not_common

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [145]:
pd.concat([ser1,ser2],axis=0) # concat will just join ...duplicate or not dosent matter

0    1
1    2
2    3
3    4
4    5
0    4
1    5
2    6
3    7
4    8
dtype: int64

In [153]:
ser = pd.Series(np.random.normal(10,5,25))

        - Percentile means that ... for eg 95 percentile... which means 95% of the observation out of the total distribution falls uder 95% and you are in the top 5% ... or you are below 5% of the total distribution

In [160]:
np.percentile(ser, q=[0, 50, 75, 100]) 

array([ 1.42657769,  9.5123633 , 13.85968853, 25.06382187])

## Calculate the frequency count of each of the unique value in the series 

In [658]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

In [659]:
ser

0     e
1     a
2     c
3     d
4     h
5     a
6     g
7     c
8     e
9     a
10    a
11    f
12    b
13    e
14    h
15    f
16    c
17    f
18    f
19    h
20    g
21    g
22    c
23    g
24    a
25    c
26    a
27    a
28    e
29    b
dtype: object

In [200]:
ser.value_counts()

b    6
a    5
d    5
g    4
e    4
c    3
f    2
h    1
dtype: int64

### keeping only top 2 frequent values and replacing all others with something else

In [1587]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1,5,[12]))

In [1588]:
ser

0     2
1     3
2     3
3     4
4     1
5     3
6     4
7     1
8     4
9     2
10    1
11    1
dtype: int32

In [1589]:
ser.value_counts().index[:2]

Int64Index([1, 3], dtype='int64')

In [1590]:
ser[~ser.isin(ser.value_counts().index[:2])] = 'zzz'

In [1591]:
ser

0     zzz
1       3
2       3
3     zzz
4       1
5       3
6     zzz
7       1
8     zzz
9     zzz
10      1
11      1
dtype: object

## How to bin a numeric series to 10 groups of equal size

In [280]:
ser = pd.Series(np.random.random(20))

In [281]:
ser

0     0.243700
1     0.651756
2     0.524920
3     0.735078
4     0.324009
5     0.851721
6     0.671774
7     0.676642
8     0.186686
9     0.012731
10    0.713571
11    0.384183
12    0.715581
13    0.052601
14    0.008409
15    0.341547
16    0.367474
17    0.800569
18    0.790596
19    0.361423
dtype: float64

In [282]:
np.round(np.linspace(0,1,10),1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.6, 0.7, 0.8, 0.9, 1. ])

In [290]:
pd.qcut(ser, q=[0 , .10, .20, .3, .5, .4, .6, .7, .8, .9, 1 ], 
       labels =['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th']).head()

0    3rd
1    6th
2    6th
3    9th
4    3rd
dtype: category
Categories (10, object): ['1st' < '2nd' < '3rd' < '4th' ... '7th' < '8th' < '9th' < '10th']

In [291]:
# Converting numpy array to dataframe

arr = np.arange(35)


In [292]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34])

In [298]:
ser = pd.Series(np.random.randint(1,10,35))
ser

0     5
1     4
2     7
3     4
4     8
5     4
6     2
7     9
8     1
9     7
10    9
11    4
12    8
13    4
14    2
15    9
16    5
17    1
18    4
19    8
20    6
21    5
22    3
23    1
24    9
25    3
26    3
27    7
28    6
29    5
30    4
31    1
32    7
33    4
34    5
dtype: int32

In [306]:
pd.DataFrame(ser.values.reshape(7,5),columns=list('abcde'))

a  b  c  d  e
0  5  4  7  4  8
1  4  2  9  1  7
2  9  4  8  4  2
3  9  5  1  4  8
4  6  5  3  1  9
5  3  3  7  6  5
6  4  1  7  4  5

In [304]:
ser.values

array([5, 4, 7, 4, 8, 4, 2, 9, 1, 7, 9, 4, 8, 4, 2, 9, 5, 1, 4, 8, 6, 5,
       3, 1, 9, 3, 3, 7, 6, 5, 4, 1, 7, 4, 5])

### Find the positions of nos. that are multiples of 3 from a series

In [1592]:
ser = pd.Series(np.random.randint(1,10,7))
ser

0    5
1    8
2    6
3    1
4    1
5    9
6    1
dtype: int32

In [1602]:
ser[ser%3==0]

2    6
5    9
dtype: int32

In [1595]:
a = ser%3 ==0
a

0    False
1    False
2     True
3    False
4    False
5     True
6    False
dtype: bool

In [1596]:
idx = np.where(ser%3==0)
idx

(array([2, 5], dtype=int64),)

In [1597]:
aa = idx[0].tolist()
aa

[2, 5]

In [1598]:
ser.iloc[aa]

2    6
5    9
dtype: int32

In [672]:
np.argwhere([a])

array([[0, 2],
       [0, 5]], dtype=int64)

In [332]:
ser[ser%3==0].index

Int64Index([6], dtype='int64')

## Extracting specific index positions from series

In [334]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))

In [335]:
ser

0     a
1     b
2     c
3     d
4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

In [336]:
ser.take([0,5,6,9])

0    a
5    f
6    g
9    j
dtype: object

In [340]:
ser.iloc[[0,5,6,9]]

0    a
5    f
6    g
9    j
dtype: object

# Stack 2 Series vertically and horizontally

In [345]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [350]:
ser1 = pd.Series(np.arange(10))
ser2 = pd.Series(list('abhishekma'))


In [355]:
ser1.append(ser2,ignore_index=False) # if True then it will keep the index formated from top to last

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
0    a
1    b
2    h
3    i
4    s
5    h
6    e
7    k
8    m
9    a
dtype: object

In [356]:
pd.concat([ser1,ser2],axis=1)

0  1
0  0  a
1  1  b
2  2  h
3  3  i
4  4  s
5  5  h
6  6  e
7  7  k
8  8  m
9  9  a

### get the positions of the items of series A in another series B

In [1603]:
ser1 = pd.Series([10,9,6,5,3,1,12,8,13])
ser2 = pd.Series([1,3,10,13])

In [1611]:
##### method1
[np.where(x == ser1)[0][0] for x in ser2]

[5, 4, 0, 8]

In [383]:
##### method 2
[pd.Index(ser1).get_loc(x) for x in ser2]

[5, 4, 0, 8]

In [1608]:
#### method 3
ser1[ser1.isin(ser2)]

0    10
4     3
5     1
8    13
dtype: int64

### mean squared error of truth and pred series

In [385]:
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

In [390]:
np.mean((truth-pred)**2)

0.2671085350049168

### Converting first character of each element of series in uppercase

In [1615]:
ser = pd.Series(['abhi', 'hi', 'DddatS', 'scIENCE'])

#### method 1 using list comprehension
pd.Series([x[0].upper() + x[1:] for x in ser])

0       Abhi
1         Hi
2     DddatS
3    ScIENCE
dtype: object

In [1616]:
##### method 2 using the title function
[x.title() for x in ser]

['Abhi', 'Hi', 'Dddats', 'Science']

In [1617]:
##### method 3 using the lambda function and title both()

ser.map(lambda x: x.title())

0       Abhi
1         Hi
2     Dddats
3    Science
dtype: object

## calculating no. of characters in each word in series

In [1618]:
ser = pd.Series(['how', 'to', 'kick', 'ass'])
ser

0     how
1      to
2    kick
3     ass
dtype: object

In [415]:
##### method 1 using list comprehension
pd.Series([len(x) for x in ser])

0    3
1    2
2    4
3    3
dtype: int64

In [1622]:
#### method 3 just using the len function in apply()
ser.apply(len)

0    3
1    2
2    4
3    3
dtype: int64

In [414]:
#### method 2 using len() method with lambda
ser.map(lambda x: len(x))

0    3
1    2
2    4
3    3
dtype: int64

## Difference of  Consequitive numbers of series

In [1626]:
ser = pd.Series([1,3,6,10,15,21,20,35])
# for i in range(len(ser)-1):
#     ser[i] = np.abs(ser[i] - ser[i+1])

In [1659]:
[str(x) for x in ser.diff().tolist() if x!=np.nan]

['nan', '2.0', '3.0', '4.0', '5.0', '6.0', '-1.0', '15.0']

In [1654]:
ser.diff().tolist()

[nan, 2.0, 3.0, 4.0, 5.0, 6.0, -1.0, 15.0]

In [437]:
ser.diff().diff().tolist()

[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]

## Converting Data-strings to a timeseries

In [438]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05'])

In [440]:
pd.to_datetime(ser)

0   2010-01-01
1   2011-02-02
2   2012-03-03
3   2013-04-04
4   2014-05-05
dtype: datetime64[ns]

In [445]:
from dateutil.parser import parse
ser.map(lambda x : parse(x))

0   2010-01-01
1   2011-02-02
2   2012-03-03
3   2013-04-04
4   2014-05-05
dtype: datetime64[ns]

In [446]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05'])

ser

0    01 Jan 2010
1     02-02-2011
2       20120303
3     2013/04/04
4     2014-05-05
dtype: object

In [450]:
ser_date_time = pd.to_datetime(ser)

In [456]:
ser_date_time.dt.day_name()

0       Friday
1    Wednesday
2     Saturday
3     Thursday
4       Monday
dtype: object

In [462]:
ser_date_time.dt.year

0    2010
1    2011
2    2012
3    2013
4    2014
dtype: int64

In [460]:
ser_date_time.dt.month_name()

0     January
1    February
2       March
3       April
4         May
dtype: object

In [468]:
### just experimenting with./... filtering the spaces
[x for x in list('123456789  ') if x!=' ']

['1', '2', '3', '4', '5', '6', '7', '8', '9']

### filtering only the integer values from the list

In [498]:
## filtering only the integer values from the list

lst = ['1', '2', '3', '4', '5', '6', '7', '8', '9','Abhi', 'bitt']

nl = []
for i in lst:
    try:
        nl.append(int(i))
    except :
        pass
nl

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [526]:
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])
ser

0    Jan 2010
1    Feb 2011
2    Mar 2012
dtype: object

In [511]:
ser = pd.to_datetime(ser)

0   2010-01-01
1   2011-02-01
2   2012-03-01
dtype: datetime64[ns]

In [536]:
from dateutil.parser import parse
ser_dt = ser.map(lambda x : parse('4'+x))

In [537]:
ser_dt

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

## How to filter out the words that contains only 2 vowels from the series

In [1667]:
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Monkey'])
ser

0     Apple
1    Orange
2      Plan
3    Python
4    Monkey
dtype: object

In [1668]:
[Counter('apple'.lower()).get(i,0) for i in list('aeiou')]

[1, 1, 0, 0, 0]

In [1679]:
Counter('apple'.lower()).get('p',0)

2

In [1669]:
from collections import Counter
mask = ser.map(lambda x : sum([Counter( x.lower() ).get(i,0) for i in list('aeiou')]) >= 2)

In [1670]:
ser[mask]

0     Apple
1    Orange
4    Monkey
dtype: object

### How to filter valid emails from series

In [578]:
import re
emails = pd.Series(['buying books at amaxon', 'abhishek@india.com','narendra@modi.com', 'abhi@co'])
pattern = '[A-Za-z0-9._%+-]+@[A-Za-z0-9._%+-]+\\.[A-Za-z]{2,4}'

mask = emails.map(lambda x : bool(re.match(pattern,x)))
emails[mask]

1    abhishek@india.com
2     narendra@modi.com
dtype: object

In [579]:
### solution 2
emails.str.findall(pattern,flags=re.IGNORECASE)

0                      []
1    [abhishek@india.com]
2     [narendra@modi.com]
3                      []
dtype: object

In [586]:
### solution 3 ...using 2 loops in list comprehension
[e[0] for e in [re.findall(pattern,email) for email in emails] if len(e)>0]

['abhishek@india.com', 'narendra@modi.com']

## get the mean of a series grouped by another series

Compute the mean of weights of each fruit

In [593]:
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1,10,10))
weights.tolist()

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]

In [595]:
print(fruit.tolist())

['carrot', 'banana', 'carrot', 'carrot', 'apple', 'banana', 'apple', 'banana', 'apple', 'carrot']


In [604]:
weights.groupby(fruit).mean()

apple     7.000000
banana    5.333333
carrot    4.500000
dtype: float64

# Eucledian dist between 2 series

In [607]:
ser1 = pd.Series(np.arange(1,11))
ser2 = pd.Series(np.arange(10,0,-1))

In [610]:
ser1.tolist()

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [611]:
sum((ser1-ser2)**2)**.5

18.16590212458495

In [612]:
np.linalg.norm(ser1-ser2)

18.16590212458495

## How to find local maxima or peaks in numeric series

get the positions of peaks values surrounded by smalleer values on both sides

In [619]:
ser = pd.Series([2,10,3,4,9,10,2,7,3])

In [623]:
np.diff(ser)

array([ 8, -7,  1,  5,  1, -8,  5, -4], dtype=int64)

In [626]:
dd = np.diff(np.sign(np.diff(ser)))
dd

array([-2,  2,  0,  0, -2,  2, -2], dtype=int64)

In [632]:
peak_locs = np.where(dd == -2)[0] +1
peak_locs

array([1, 5, 7], dtype=int64)

In [621]:
ser.cumsum()

0     2
1    12
2    15
3    19
4    28
5    38
6    40
7    47
8    50
dtype: int64

In [622]:
ser.cummax()

0     2
1    10
2    10
3    10
4    10
5    10
6    10
7    10
8    10
dtype: int64

## Replace missing spaces in a string with the least frequent character

In [713]:
my_str = 'dbc deb abed gade'

In [735]:
a = [i for i in my_str.split()[::-1]]
a

['gade', 'abed', 'deb', 'dbc']

In [738]:
res =''
for i in a:
    res = res +' '+ i

res.strip()

'gade abed deb dbc'

In [639]:
Counter([x for x in list(my_str) if x !=' '])

Counter({'d': 4, 'b': 3, 'c': 1, 'e': 3, 'a': 2, 'g': 1})

### Counting the frequency without using the counter function

In [776]:
st = 'aaaabb  hhii'
dct = {}
ctr = 1
for i in st:
    if i in dct:
        dct[i]+=1
    else:
        dct[i] = 1
    

In [777]:
dct

{'a': 4, 'b': 2, ' ': 2, 'h': 2, 'i': 2}

In [765]:
dct['a'] = 

In [756]:
Counter(st)

Counter({'a': 2, 'b': 2, 'h': 2, 'i': 2})

In [743]:
dct

'{}aabbhhii'

In [635]:
Counter(my_str)

Counter({'d': 4, 'b': 3, 'c': 1, ' ': 3, 'e': 3, 'a': 2, 'g': 1})

In [642]:
pd.Series(list(my_str)).value_counts()

d    4
     3
e    3
b    3
a    2
c    1
g    1
dtype: int64

# How to fill an intermittent time series so all missing dates show up with values of previous non-missing date

ser is having missing dates and values . now lets make the missing dates appear and fill up with the dates from previous dates

In [783]:
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
ser

2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     NaN
dtype: float64

In [784]:
ser.resample('D').ffill()

2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN
Freq: D, dtype: float64

In [792]:
a = pd.Series([1,2,4,6,8,10], index=[1,3,6,8,9,2])
a

1     1
3     2
6     4
8     6
9     8
2    10
dtype: int64

## Compute the autocorrelations of a numeric series?

In [805]:
ser = pd.Series(np.arange(20)+np.random.normal(1,10,20))
ser

0     21.869914
1      0.396771
2      3.482232
3     16.478963
4     -1.838379
5      9.639020
6      5.913962
7     23.156984
8     -2.545655
9      6.724886
10    16.970017
11    11.836418
12     4.864228
13     7.365451
14    14.791933
15     5.745531
16    24.782668
17    26.885762
18    35.997662
19    25.563855
dtype: float64

In [810]:
[ser.autocorr(x).round(2) for x in range(10)]

[1.0, 0.26, 0.26, 0.2, 0.16, -0.15, -0.19, 0.49, -0.14, -0.04]

## import only nth row from a csv file to create a dataframe

Lets import only 50th row!

In [825]:
#### using chunks and for loop

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', chunksize=50)
type(df)

pandas.io.parsers.TextFileReader

In [826]:
df2 = pd.DataFrame()
for chunk in df:
    df2 = df2.append(chunk.iloc[0,:])

In [828]:
df2.head()

age       b  chas     crim     dis  indus  lstat  medv    nox  ptratio  \
0    65.2  396.90   0.0  0.00632  4.0900   2.31   4.98  24.0  0.538     15.3   
50   45.7  395.56   0.0  0.08873  6.8147   5.64  13.45  19.7  0.439     16.8   
100  79.9  394.76   0.0  0.14866  2.7778   8.56   9.42  27.5  0.520     20.9   
150  97.3  372.80   0.0  1.65660  1.6180  19.58  14.10  21.5  0.871     14.7   
200  13.9  384.30   0.0  0.01778  7.6534   1.47   4.45  32.9  0.403     17.0   

     rad     rm    tax    zn  
0    1.0  6.575  296.0  18.0  
50   4.0  5.963  243.0  21.0  
100  5.0  6.727  384.0   0.0  
150  5.0  6.122  403.0   0.0  
200  3.0  7.135  402.0  95.0

In [830]:
#### using the csv reader
import csv
with open('BostonHousing.csv', 'r') as f:
    reader = csv.reader(f)
    out = []
    for i, row in enumerate(reader):
        if i%50 == 0 :
            out.append(row)

FileNotFoundError: [Errno 2] No such file or directory: 'BostonHousing.csv'

In [ ]:
df2 = pd.DataFrame(out[1:], columns=out[0])
df2.head

## Changing the column values when importing csv to a dataframe

In [832]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv',
                 converters={'medv' : lambda x :'High' if float(x)>25 else 'Low' })


In [833]:
df.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98   Low  
1  396.90   9.14   Low  
2  392.83   4.03  High  
3  394.63   2.94  High  
4  396.90   5.33  High

In [ ]:
with open('anyfilename.csv') as f:
    reader = csv.reader(f)
    out = []
    for i, row in enumerate(reader):
        out.apend(row)

df =  pd.DataFrame(out[1:],columns=out[0])
print(df.head())
    

## Creating a dataframe with rows as strides from given series?

In [834]:
L = pd.Series(range(15))

In [835]:
L

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
dtype: int64

## calculating the sum of all the elements in the window (any window size)

In [847]:
lst=[]
sm = 0
for i in range(len(L)-3):
    sm=0
    for j in range(i,i+3):
        sm = sm + L[j]
        
    lst.append(sm)

In [848]:
L.tolist()

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [849]:
print(lst)

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36]


## to load only specific columns while loading csv file .... usecols=['a','b]

In [851]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.head()

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   
3         Audi      100  Midsize        NaN   37.7       44.6      19.0   
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                None      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

In [855]:
df.dtypes.value_counts()

float64    18
object      9
dtype: int64

In [858]:
df['DriveTrain'].value_counts()

Front    61
Rear     15
4WD      10
Name: DriveTrain, dtype: int64

In [868]:
df['Manufacturer'].unique()

array(['Acura', nan, 'Audi', 'BMW', 'Buick', 'Cadillac', 'Chevrolet',
       'Chrysler', 'Dodge', 'Eagle', 'Ford', 'Geo', 'Honda', 'Hyundai',
       'Infiniti', 'Lexus', 'Lincoln', 'Mazda', 'Mercedes-Benz',
       'Mercury', 'Mitsubishi', 'Nissan', 'Oldsmobile', 'Plymouth',
       'Pontiac', 'Saab', 'Saturn', 'Subaru', 'Suzuki', 'Toyota',
       'Volkswagen', 'Volvo'], dtype=object)

In [888]:
np.max(df['Price'])

61.9

In [890]:
df.loc[df['Price']==np.max(df['Price']), ['Manufacturer', 'Model', 'Type']]

Manufacturer Model     Type
58  Mercedes-Benz  300E  Midsize

In [891]:
df.iloc[58]

Manufacturer               Mercedes-Benz
Model                               300E
Type                             Midsize
Min.Price                           43.8
Price                               61.9
Max.Price                           80.0
MPG.city                            19.0
MPG.highway                         25.0
AirBags               Driver & Passenger
DriveTrain                          Rear
Cylinders                              6
EngineSize                           3.2
Horsepower                         217.0
RPM                               5500.0
Rev.per.mile                      2220.0
Man.trans.avail                       No
Fuel.tank.capacity                  18.5
Passengers                           5.0
Length                               NaN
Wheelbase                          110.0
Width                               69.0
Turn.circle                         37.0
Rear.seat.room                       NaN
Luggage.room                        15.0
Weight          

In [899]:
row, col = np.where(df.values == np.max(df['Price']))
row, col

(array([58], dtype=int64), array([4], dtype=int64))

In [898]:
df.values

array([['Acura', 'Integra', 'Small', ..., 2705.0, 'non-USA',
        'Acura Integra'],
       [nan, 'Legend', 'Midsize', ..., 3560.0, 'non-USA', 'Acura Legend'],
       ['Audi', '90', 'Compact', ..., 3375.0, 'non-USA', 'Audi 90'],
       ...,
       ['Volkswagen', 'Corrado', 'Sporty', ..., 2810.0, 'non-USA',
        'Volkswagen Corrado'],
       ['Volvo', '240', 'Compact', ..., 2985.0, 'non-USA', 'Volvo 240'],
       [nan, '850', 'Midsize', ..., 3245.0, 'non-USA', 'Volvo 850']],
      dtype=object)

In [904]:
# df.iat[row[0], col[0]],
df.iloc[row[0],col[0]]

61.9

In [905]:
df.at[row[0], 'Price']

61.9

In [909]:
df.get(row[0], 'Price')

'Price'

The difference between iat - iloc  vs at - loc is:

- iat , iloc accepts row and column numbers.
- at , loc accepts index and column names

## Renaming columns

In [912]:
df.rename(columns={'Type' : 'CarType'})

Manufacturer    Model  CarType  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0   
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2          Audi       90  Compact       25.9   29.1       32.3      20.0   
3          Audi      100  Midsize        NaN   37.7       44.6      19.0   
4           BMW     535i  Midsize        NaN   30.0        NaN      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0   
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0   
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0   
91        Volvo      240  Compact       21.8   22.7       23.5      21.0   
92          NaN      850  Midsize       24.8   26.7       28.5      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                None      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                None      Front  ...        7.0   187.0   
89         30.0                None      Front  ...        5.0   180.0   
90         25.0                None      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

In [915]:
df.columns = df.columns.map(lambda x : x.replace('.','_'))
df.columns

Index(['Manufacturer', 'Model', 'Type', 'Min_Price', 'Price', 'Max_Price',
       'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
       'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
       'Make'],
      dtype='object')

In [940]:
(df.isna().sum())

Manufacturer           4
Model                  1
Type                   3
Min_Price              7
Price                  2
Max_Price              5
MPG_city               9
MPG_highway            2
AirBags                6
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev_per_mile           6
Man_trans_avail        5
Fuel_tank_capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn_circle            5
Rear_seat_room         4
Luggage_room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64

In [922]:
df.isna().values.any()

True

In [931]:
for i in df.columns:
    print('{}            is having          {} null values   '.format(i,df[i].isnull().mean()))

Manufacturer            is having          0.043010752688172046 null values   
Model            is having          0.010752688172043012 null values   
Type            is having          0.03225806451612903 null values   
Min_Price            is having          0.07526881720430108 null values   
Price            is having          0.021505376344086023 null values   
Max_Price            is having          0.053763440860215055 null values   
MPG_city            is having          0.0967741935483871 null values   
MPG_highway            is having          0.021505376344086023 null values   
AirBags            is having          0.06451612903225806 null values   
DriveTrain            is having          0.07526881720430108 null values   
Cylinders            is having          0.053763440860215055 null values   
EngineSize            is having          0.021505376344086023 null values   
Horsepower            is having          0.07526881720430108 null values   
RPM            is having   

In [934]:
df.apply(lambda x:x.isnull().sum())

Manufacturer           4
Model                  1
Type                   3
Min_Price              7
Price                  2
Max_Price              5
MPG_city               9
MPG_highway            2
AirBags                6
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev_per_mile           6
Man_trans_avail        5
Fuel_tank_capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn_circle            5
Rear_seat_room         4
Luggage_room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64

## Selecting specific column as a dataframe instead of series

In [946]:
df[['Model']]

Model
0   Integra
1    Legend
2        90
3       100
4      535i
..      ...
88  Eurovan
89   Passat
90  Corrado
91      240
92      850

[93 rows x 1 columns]

## How to change the order of columns of a dataframe?

In [956]:
df = pd.DataFrame(np.arange(20).reshape(-1,5), columns=list('abcde'))
df

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [958]:
### interchanging columns a & c
df[list('cbade')]

c   b   a   d   e
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19

In [969]:
def switch_cols(df, col1=None, col2=None):
    colnames = df.columns.tolist()
    i1, i2 = colnames.index(col1), colnames.index(col2)
    colnames[i2], colnames[i1] = colnames[i1], colnames[i2]
    return df[colnames]
    

switch_cols(df, 'a', 'c')
    

c   b   a   d   e
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19

In [961]:
df.columns.tolist().index('e')

4

In [968]:
df.columns.tolist()[4]

'e'

In [971]:
df[sorted(df.columns, reverse=True)]

e   d   c   b   a
0   4   3   2   1   0
1   9   8   7   6   5
2  14  13  12  11  10
3  19  18  17  16  15

## Expressing each value of a dataframe as percentage

In [974]:
df = pd.DataFrame(np.random.random(4), columns=['random'])

In [975]:
df

random
0  0.620606
1  0.338600
2  0.894712
3  0.643624

In [989]:
df.style.format({'random' : '{0:.2%}'.format,})

## Filtering nth row in dataframe

For example showing every 20th row or 10th row data 

In [990]:
df.head()

random
0  0.620606
1  0.338600
2  0.894712
3  0.643624

In [1001]:
df.iloc[::2, :]

random
0  0.620606
2  0.894712

# How to get the row number of the nth largest value in a column

In [1075]:
df = pd.DataFrame(np.random.randint(1,30,30).reshape(10,-1), columns=list('abc'))

In [1076]:
df

a   b   c
0   9  14  16
1  27   9  21
2  29   4  26
3   7   2  13
4  16  20   3
5  15   8  22
6   8  27   7
7  24  13  24
8   3  23   4
9   9  21  18

In [1095]:
ser = pd.Series([5,7,3,2,9,10])
ser

0     5
1     7
2     3
3     2
4     9
5    10
dtype: int64

Now we can get the nth largest from this

In [1117]:
ser.sort_values()[::-1].reset_index().drop('index',axis=1)[0]

0    10
1     9
2     7
3     5
4     3
5     2
Name: 0, dtype: int64

In [1132]:
ser.iloc[ser.argsort()[::-1].reset_index()[0][2]]

7

In [1093]:
df['a'].argsort() # argsort will tell you that if you order these indexes then you will get desc/asc order results

0    8
1    3
2    6
3    0
4    9
5    5
6    4
7    7
8    1
9    2
Name: a, dtype: int64

In [1087]:
df['a'].argsort()[::-1][1]

3

In [1019]:
n =5
df['a'].argsort()[::-1][n]

9

In [1028]:
df['b'].sort_values()

8     2
0     3
6     8
7    10
1    15
2    17
9    18
3    27
4    27
5    29
Name: b, dtype: int32

In [1032]:
df['b'].argsort()[::-1] # arg sort gives you the index by which the series should be sorted

9    5
8    4
7    3
6    9
5    2
4    1
3    7
2    6
1    0
0    8
Name: b, dtype: int64

In [1033]:
df['b'].iloc[7]

10

## Position of the nth largest value greater than a given value?

Find the position of the 2nd largest value greater than the mean

In [1137]:
ser = pd.Series(np.random.randint(1,100,15))
ser

0     46
1     48
2     76
3      6
4     66
5     23
6     41
7     16
8     48
9     11
10    68
11     8
12    91
13    90
14    73
dtype: int32

In [1139]:
## calculating the mean first
mn = ser.mean()
mn

47.4

Simple solution using the sort_values(). If you go with the argsort() then you will be getting the indexes only

In [1161]:
ser[ser>mn].sort_values().reset_index()[0]

0    48
1    48
2    66
3    68
4    73
5    76
6    90
7    91
Name: 0, dtype: int32

In [1050]:
ser[ser.sort_values()>mn]

1     55
2     74
3     56
5     90
10    72
11    48
13    94
14    55
dtype: int32

In [1056]:
np.argwhere([ser > ser.mean()])[2]

array([0, 3], dtype=int64)

# How to get the last n rows of a dataframe with row sum > 100

Get the last 2 rows of the df whose row sum is >100

In [1171]:
df = pd.DataFrame(np.random.randint(10,40,60).reshape(-1,4))
df

0   1   2   3
0   13  34  29  34
1   12  10  38  18
2   10  32  14  25
3   38  27  28  15
4   37  32  18  11
5   17  33  29  31
6   39  23  10  26
7   25  18  27  33
8   15  17  26  30
9   15  13  19  17
10  16  36  35  33
11  13  21  11  26
12  18  32  13  30
13  39  26  10  34
14  15  27  25  17

In [1174]:
(df.iloc[14])

0    15
1    27
2    25
3    17
Name: 14, dtype: int32

In [1175]:
sum(df.iloc[14])

84

In [1178]:
df.shape[0]

15

In [1199]:
idx = []
for i in range(df.shape[0]):
    if sum(df.iloc[i]) > 100:
        idx.append(i)

print(idx)
df.iloc[idx][-2:]       
        

[0, 3, 5, 7, 10, 13]


0   1   2   3
10  16  36  35  33
13  39  26  10  34

In [1200]:
## solution 2

rowsums = df.apply(np.sum, axis=1)
rowsums

0     110
1      78
2      81
3     108
4      98
5     110
6      98
7     103
8      88
9      64
10    120
11     71
12     93
13    109
14     84
dtype: int64

In [1203]:
df.iloc[np.where(rowsums>100)[0][-2:],:]

0   1   2   3
10  16  36  35  33
13  39  26  10  34

# How to find the cap outliers from a series or dataframe column?

Replace all values of ser in the lower 5%ile and greater than 95%ile with respective 5th and 95th %ile value

In [1222]:
ser = pd.Series(np.logspace(-2,2,30))

In [1223]:
ser

0       0.010000
1       0.013738
2       0.018874
3       0.025929
4       0.035622
5       0.048939
6       0.067234
7       0.092367
8       0.126896
9       0.174333
10      0.239503
11      0.329034
12      0.452035
13      0.621017
14      0.853168
15      1.172102
16      1.610262
17      2.212216
18      3.039195
19      4.175319
20      5.736153
21      7.880463
22     10.826367
23     14.873521
24     20.433597
25     28.072162
26     38.566204
27     52.983169
28     72.789538
29    100.000000
dtype: float64

In [1215]:
low, high = ser.quantile([0.05, 0.95])

In [1219]:
np.round(low,2), np.round(high)

(0.02, 64.0)

In [1224]:
ser[ser<np.round(low,2)] = np.round(low,2)
ser[ser>np.round(high,2)] = np.round(high,2)

# How to swap 2 Rows in a Dataframe?


In [1307]:
def swap_rows(df, a, b):
    
    a1 = df.iloc[a,:].copy()
    b1 = df.iloc[b,:].copy()
    df.iloc[a,:], df.iloc[b,:] = b1, a1
    return df
    

    

In [1361]:
df = pd.DataFrame({'a' : [11,21,31,41,51],'b' : [1,2,3,4,5]})
df

a  b
0  11  1
1  21  2
2  31  3
3  41  4
4  51  5

In [1362]:
swap_rows(df,2,3)

a  b
0  11  1
1  21  2
2  41  4
3  31  3
4  51  5

## Swapping columns

In [1363]:
def swap_columns(df, col1,col2) :
    aa, bb = df.loc[:,col1].values.copy(), df.loc[:,col2].values.copy()
    df.loc[:,col1], df.loc[:,col2] = bb, aa

In [1364]:
swap_columns(df, 'a', 'b')

In [1365]:
df

a   b
0  1  11
1  2  21
2  4  41
3  3  31
4  5  51

## Reversing the rows in a  DataFrame

In [1368]:
df = pd.DataFrame(np.arange(25).reshape(5,-1))
df

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [1375]:
df.iloc[::,::-1]

4   3   2   1   0
0   4   3   2   1   0
1   9   8   7   6   5
2  14  13  12  11  10
3  19  18  17  16  15
4  24  23  22  21  20

In [1380]:
df

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [1386]:
df.iloc[1:3:,1:3:]

1   2
1   6   7
2  11  12

## Creating one hot encoding and appending the new columns

In [1388]:
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))
df

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [1390]:
dm = pd.get_dummies(df['a'])
dm

0   5   10  15  20
0   1   0   0   0   0
1   0   1   0   0   0
2   0   0   1   0   0
3   0   0   0   1   0
4   0   0   0   0   1

In [1394]:
pd.concat([pd.get_dummies(df['a']),df[list('bcde')]],axis=1)

0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24

## which column contains the highest number of row- wise  maximum values?

Obtain the column name with the highest no. of row-wise maximum in df

In [1409]:
df = pd.DataFrame(np.random.randint(1,100,40).reshape(10,-1))
df

0   1   2   3
0  35  89  18   7
1  26  90  19  88
2  20  65  63  84
3  69  43  68  57
4  15  53  96  22
5  18  51   4  66
6  34  94  46  56
7  15  92  36  13
8  15  66  90  15
9  98  92  47   5

In [1404]:
df = np.where(df%2==0, df*10, df)

In [1405]:
df

array([[ 43,  80, 620,  29],
       [600,  55,  20,  89],
       [720,  97, 200,  63],
       [  1, 840,  41, 900],
       [  7,  40, 600,  80],
       [120,  13, 200,  97],
       [900, 740, 100,  55],
       [ 17, 380, 980, 740],
       [ 13, 560,  93,  67],
       [700,  15,   1,  47]])

In [1482]:
df.iloc[::,::]


0   1   2   3
0  35  89  18   7
1  26  90  19  88
2  20  65  63  84
3  69  43  68  57
4  15  53  96  22
5  18  51   4  66
6  34  94  46  56
7  15  92  36  13
8  15  66  90  15
9  98  92  47   5

In [1415]:
df.apply(np.argmax, axis=1)

0    1
1    1
2    3
3    0
4    2
5    3
6    1
7    1
8    2
9    0
dtype: int64

In [1430]:
df.apply(np.argmax, axis=1).value_counts() #.index[0]

1    4
0    2
2    2
3    2
dtype: int64

In [1434]:
df

0   1   2   3
0  35  89  18   7
1  26  90  19  88
2  20  65  63  84
3  69  43  68  57
4  15  53  96  22
5  18  51   4  66
6  34  94  46  56
7  15  92  36  13
8  15  66  90  15
9  98  92  47   5

##  Maximum of all the columns 

In [1443]:
res = []
for i in df.columns:
    res.append(df[i].max())
    
res
    
    

[98, 94, 96, 88]

## Maximum of all the rows

In [1451]:
res = []
for i in df.index:
    res.append(df.iloc[i,:].argmax())
res

[1, 1, 3, 0, 2, 3, 1, 1, 2, 0]

# Create a column that contains the penultimate value in each row?

create a new column penultimate which has the second largest value of each row of df

In [1484]:
df = pd.DataFrame(np.random.randint(1,100,80).reshape(8,-1))
df

0   1   2   3   4   5   6   7   8   9
0  77  85  85  79  69  54  76  15  63  78
1  66  66  87  62  33  26  87  79  61  87
2  39  56  53   4  39  95  44  24  75   1
3  83   1  65  50  29  98  58   9  94  27
4  30  84  45  66  97  88  80  96  89   2
5  30  71  23  88  84  64  63  46  11  29
6  69  23  46  93  64  66  56  34  69  71
7  78  10  23  95  69  92  20  88  47  81

In [1485]:
out = df.apply(lambda x : x.sort_values().unique()[-2], axis=1)
df['penultimate'] = out
df
    
    

0   1   2   3   4   5   6   7   8   9  penultimate
0  77  85  85  79  69  54  76  15  63  78           79
1  66  66  87  62  33  26  87  79  61  87           79
2  39  56  53   4  39  95  44  24  75   1           75
3  83   1  65  50  29  98  58   9  94  27           94
4  30  84  45  66  97  88  80  96  89   2           96
5  30  71  23  88  84  64  63  46  11  29           84
6  69  23  46  93  64  66  56  34  69  71           71
7  78  10  23  95  69  92  20  88  47  81           92

## Normalize all columns in dataframe

In [1486]:
df = pd.DataFrame(np.random.randint(1,100,80).reshape(8,-1))
df

0   1   2   3   4   5   6   7   8   9
0  81  53  98  53  90  18  69   2   5  48
1  39  52  54  79   9  39  79  71  89  28
2  88  13  50  64  21  17  79   1   1  53
3  93  98  14  65  99  94  16  25  76  56
4  49  22   2   5  91  84  92  26  80  58
5  34   2   4  38  86  78  51   5  74   6
6  40  59  37  84  53  46  15  32  63  79
7  82  22  10  23  25  72  52  63  31  95

In [1487]:
out = df.apply(lambda x : ((x.max() - x)/x.max() - x.min()).round(2))
out

0     1     2     3     4      5      6     7     8     9
0 -33.87 -1.54 -2.00 -4.63 -8.91 -16.19 -14.75 -0.03 -0.06 -5.51
1 -33.42 -1.53 -1.55 -4.94 -8.09 -16.41 -14.86 -1.00 -1.00 -5.29
2 -33.95 -1.13 -1.51 -4.76 -8.21 -16.18 -14.86 -0.01 -0.01 -5.56
3 -34.00 -2.00 -1.14 -4.77 -9.00 -17.00 -14.17 -0.35 -0.85 -5.59
4 -33.53 -1.22 -1.02 -4.06 -8.92 -16.89 -15.00 -0.37 -0.90 -5.61
5 -33.37 -1.02 -1.04 -4.45 -8.87 -16.83 -14.55 -0.07 -0.83 -5.06
6 -33.43 -1.60 -1.38 -5.00 -8.54 -16.49 -14.16 -0.45 -0.71 -5.83
7 -33.88 -1.22 -1.10 -4.27 -8.25 -16.77 -14.57 -0.89 -0.35 -6.00

In [1489]:
out2 = df.apply(lambda x : ((x-x.mean())/x.std()).round(2))
out2

0     1     2     3     4     5     6     7     8     9
0  0.71  0.41  1.95  0.06  0.84 -1.26  0.43 -0.97 -1.35 -0.18
1 -0.97  0.38  0.62  1.00 -1.37 -0.57  0.77  1.60  1.05 -0.90
2  0.99 -0.87  0.50  0.46 -1.04 -1.30  0.77 -1.01 -1.47  0.00
3  1.19  1.85 -0.59  0.49  1.08  1.26 -1.41 -0.12  0.67  0.11
4 -0.57 -0.58 -0.96 -1.68  0.86  0.93  1.22 -0.08  0.79  0.19
5 -1.17 -1.22 -0.90 -0.49  0.73  0.73 -0.19 -0.86  0.62 -1.70
6 -0.93  0.60  0.10  1.18 -0.17 -0.33 -1.44  0.14  0.30  0.95
7  0.75 -0.58 -0.71 -1.03 -0.93  0.53 -0.16  1.30 -0.61  1.53

# calculate correlation with the succeeding row

## Replacing both the diagonals by 0

In [1491]:
df = pd.DataFrame(np.arange(100).reshape(10,-1))
df

0   1   2   3   4   5   6   7   8   9
0   0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2  20  21  22  23  24  25  26  27  28  29
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49
5  50  51  52  53  54  55  56  57  58  59
6  60  61  62  63  64  65  66  67  68  69
7  70  71  72  73  74  75  76  77  78  79
8  80  81  82  83  84  85  86  87  88  89
9  90  91  92  93  94  95  96  97  98  99

In [1498]:
[df.iloc[x,x]=0 for x in range(df.shape[0])]

SyntaxError: invalid syntax (<ipython-input-1498-54d946000eec>, line 1)

In [1507]:
df.shape

(10, 10)

In [1502]:
for x in range(df.shape[0]):
    df.iloc[x,x] = 0
    df.iloc[x,df.shape[1]-x-1]=0
    
    

In [1503]:
df

0   1   2   3   4   5   6   7   8   9
0   0   1   2   3   4   5   6   7   8   0
1  10   0  12  13  14  15  16  17   0  19
2  20  21   0  23  24  25  26   0  28  29
3  30  31  32   0  34  35   0  37  38  39
4  40  41  42  43   0   0  46  47  48  49
5  50  51  52  53   0   0  56  57  58  59
6  60  61  62   0  64  65   0  67  68  69
7  70  71   0  73  74  75  76   0  78  79
8  80   0  82  83  84  85  86  87   0  89
9   0  91  92  93  94  95  96  97  98   0

In [1506]:
df.iloc[1,1]

0